#!/bin/bash

THIS_DIR="$(cd "$(dirname "$0")"; pwd)"

INNER_SCRIPT="rebuild_image_for_phusion_baseimage-docker_inside_container"

cd $THIS_DIR || exit 1
$THIS_DIR/bin/run_in_image_builder_container "$THIS_DIR/$INNER_SCRIPT" || { echo "ERROR: $(basename $0): FAILED to rebuild phusion base image" >&2; exit 1; }

docker image ls | grep phusion_baseimage-docker || exit 1

exit 0
