#!/bin/bash

THIS_DIR="$(cd "$(dirname "$0")"; pwd)"
IMAGE_REPOS_DIR="$THIS_DIR/image_repos"

function main {
    $THIS_DIR/build_image_builder_image || { echo "ERROR: could not build image_builder_image" >&2; exit 1; }
    echo "finished building image_builder_image"

    cd $THIS_DIR
    mkdir -p $IMAGE_REPOS_DIR

    for GITHUB_REPO_NAME in \
        phusion/baseimage-docker \
        phusion/passenger-docker \
        broadinstitute/kdux-rails-baseimage
    do
        rebuild_docker_image_from_repo $GITHUB_REPO_NAME
    done
}

function rebuild_docker_image_from_repo {
    echo
    echo "rebuilding docker image from repo: $GITHUB_REPO_NAME"
    echo "----------------------------------------------------"

    GITHUB_REPO_NAME="$1"

    CLONE_REPO="git@github.com:$GITHUB_REPO_NAME.git"

    CLONE_DIR_NAME="$(echo $GITHUB_REPO_NAME | sed 's/\//_/' )"
    CLONE_DIR="$IMAGE_REPOS_DIR/$CLONE_DIR_NAME"

    if ! [ -d  $CLONE_DIR ]; then
        git clone $CLONE_REPO $CLONE_DIR || exit 1
    fi
    pushd $CLONE_DIR || exit 1
    git checkout -- .
    git pull || exit 1
    echo "$CLONE_DIR up to date!"

    REBUILD_SCRIPT="$THIS_DIR/rebuild_image_for_$CLONE_DIR_NAME"

    $REBUILD_SCRIPT || { echo "ERROR: $REBUILD_SCRIPT failed" >&2; exit 1; }
    echo "$REBUILD_SCRIPT finished."

    popd
}

main "$@"
