#!/bin/bash

# USAGE: run with no arguments on a system with all prequisites installed to build the image. See also: local_build
# TODO TODO: maybe commit some todo's and grep for them at the end of the test job?

THIS_DIR="$(cd "$(dirname "$BASH_SOURCE")"; pwd)"
BASE_DIR="$(dirname $THIS_DIR)"
BIN="$BASE_DIR/lib/bin"
BASH_INCLUDE="$BASE_DIR/lib/bash_include"

. $BASH_INCLUDE/show_banner.bash
. $BASH_INCLUDE/bash_utils.bash
. $BASH_INCLUDE/dockerhub.bash

function main {

    force_pull_base_image || exit_with_error_message "FAILED to force pull base image."

    $BIN/rebuild_phusion_baseimage || exit_with_error_message "FAILED to rebuild phusion base image"
    $BIN/rebuild_phusion_passenger_image || exit_with_error_message "FAILED to rebuild phusion passenger image"
    $BIN/rebuild_image || exit_with_error_message "FAILED to build docker image"
}

# Forcing the true latest version of $BASE_IMAGE .
function force_pull_base_image {
    echo
    echo '########################################'
    echo "##  pulling fresh BASE_IMAGE $BASE_IMAGE"
    echo '########################################'

    docker_force_pull $BASE_IMAGE || exit_with_error_message "FAILED to pull base image $BASE_IMAGE ."
    echo "showing image history for \"$BASE_IMAGE\":"
    docker history -H=false --no-trunc $BASE_IMAGE
    echo "showing image inspect for \"$BASE_IMAGE\":"
    docker inspect $BASE_IMAGE
}

main "$@"
