#!/bin/bash

# USAGE: run with no arguments to build the image using a standardized docker container for convenient development

THIS_DIR="$(cd "$(dirname "$BASH_SOURCE")"; pwd)"
BASE_DIR="$(dirname $THIS_DIR)"
BIN="$BASE_DIR/lib/bin"
BASH_INCLUDE="$BASE_DIR/lib/bash_include"

. $BASH_INCLUDE/show_banner.bash
. $BASH_INCLUDE/bash_utils.bash

$BIN/build_image_builder_image || exit_with_error_message "Could not build image_builder image"
echo "finished building image_builder image"

$BIN/run_in_image_builder_container $THIS_DIR/build || exit 1
