#!/bin/bash

THIS_DIR="$(cd "$(dirname "$0")"; pwd)"
BASE_DIR="$(dirname $THIS_DIR)"
BIN="$BASE_DIR/lib/bin"

$BIN/build_image_builder_image || { echo "ERROR: could not build image_builder image" >&2; exit 1; }
echo "finished building image_builder image"

$BIN/run_in_image_builder_container $THIS_DIR/build || exit 1
