#!/bin/bash

# USAGE: run this with no argumants to publish the image that was built. Or better yet, don't run this, and let the jenkins job take care of it.

THIS_DIR="$(cd "$(dirname "$BASH_SOURCE")"; pwd)"
BASE_DIR="$(dirname $THIS_DIR)"
BASH_INCLUDE="$BASE_DIR/lib/bash_include"

. $BASH_INCLUDE/config.bash
. $BASH_INCLUDE/bash_utils.bash
. $BASH_INCLUDE/dockerhub.bash

# TODO: should this fail if you try to run it locally instead of from jenkins? at least if you don't pass -f/--force? maybe we should bake username/hostname into the image for traceability instead?
# TODO: publish version 1.0.

function main {
    assert_main_version_unused

    for PUBLISH_VERSION in "$MAIN_VERSION" "latest";do
        docker tag "$MAIN_IMAGE_FULLNAME:candidate" "$MAIN_IMAGE_FULLNAME:$PUBLISH_VERSION" || { echo "ERROR: $(basename $0): failed to tag $MAIN_IMAGE_NAME with $PUBLISH_VERSION ">&2; exit 1; }
        docker image ls | grep "\\b$MAIN_IMAGE_FULLNAME\\b" | grep "\\b$PUBLISH_VERSION\\b" || exit 1 #confirm taggging worked
        docker push "$MAIN_IMAGE_FULLNAME:$PUBLISH_VERSION" || { echo "ERROR: $(basename $0): failed to push $MAIN_IMAGE_FULLNAME:$PUBLISH_VERSION ">&2; exit 1; } # TODO: check if it failed because of docker login being needed
        echo published $MAIN_IMAGE_FULLNAME:$PUBLISH_VERSION
    done

}

main "$@"
