#!/bin/bash

# USAGE: run with no arguments to validate the image with some basic tests.

THIS_DIR="$(cd "$(dirname "$BASH_SOURCE")"; pwd)"
BASE_DIR="$(dirname $THIS_DIR)"
BASH_INCLUDE="$BASE_DIR/lib/bash_include"
BIN="$BASE_DIR/lib/bin"

. $BASH_INCLUDE/config.bash
. $BASH_INCLUDE/bash_utils.bash
. $BASH_INCLUDE/dockerhub.bash

function main {
    test_serving_a_page
    test_for_unpublished_changes
    exit 0
}

function test_serving_a_page {
    $BIN/build_test_image || { echo "ERROR: $(basename $0): FAILED to build test image" >&2; exit 1; }

    TEST_CONTAINER_NAME="${TEST_IMAGE_NAME}_container"
    docker stop $TEST_CONTAINER_NAME 2>/dev/null
    echo DEBUG: trying docker run...
    docker run --rm -d \
        --name "${TEST_CONTAINER_NAME}" \
        $TEST_IMAGE_FULLNAME \
    || exit_with_error_message "FAILED to run test image $MAIN_IMAGE_FULLNAME:candidate $(grep FROM Dockerfile|head -n 1)  (at $BASH_SOURCE:$LINENO)"

    TEST_CONTAINER_IPADDR="$(docker inspect -f "{{.NetworkSettings.IPAddress }}" $TEST_CONTAINER_NAME)"

    curl_output="$(curl -v --connect-timeout 2 --retry 6 --retry-delay 3 "http://$TEST_CONTAINER_IPADDR/index.nginx-debian.html" 2>&1 )"; curl_exit_code="$?"

    docker stop $TEST_CONTAINER_NAME || { echo "ERROR: could not stop container \"$TEST_CONTAINER_NAME\"! (at $BASH_SOURCE:$LINENO)" >&2; exit 1; }
    $BIN/delete_test_image || { echo "ERROR: $(basename $0): FAILED to delete test image" >&2; exit 1; }

    if [ "$curl_exit_code" -eq 0 ];then
        echo "curl succeeded!" >&2
    else
        echo "$curl_output"| tail -n 3 >&2 # TODO: limit output
        echo "ERROR ($curl_exit_code): FAILED to curl page from test container! (at $BASH_SOURCE:$LINENO)" >&2
        exit 1
    fi

    echo "HOORAY! The test container was able to serve a page."
    return 0
}

function test_for_unpublished_changes {
    docker_force_pull "$MAIN_IMAGE_FULLNAME:latest" || exit_with_error_message "could not pull fresh $MAIN_IMAGE_FULLNAME:latest from network (at $BASH_SOURCE:$LINENO)"
    latest_image_hash="$(get_docker_hash_for_image ${MAIN_IMAGE_FULLNAME}:latest)" || exit 1
    candidate_image_hash="$(get_docker_hash_for_image ${MAIN_IMAGE_FULLNAME}:candidate)" || exit 1
    if [ "$latest_image_hash" != "$candidate_image_hash" ]; then
        assert_main_version_unused
    fi

}

function docker_force_pull {
    local IMAGE="$1"

    if docker inspect $IMAGE --format '.' >/dev/null 2>&1; then # if IMAGE exists
        docker tag $IMAGE temp || { echo "ERROR: failed at $BASH_SOURCE:$LINENO" >&2; return 1; }
        docker rmi $IMAGE || { echo "ERROR: failed at $BASH_SOURCE:$LINENO" >&2; return 1; }
    fi

    docker pull $IMAGE || { echo "ERROR: failed at $BASH_SOURCE:$LINENO" >&2; return 1; }

    if docker inspect temp --format '.' >/dev/null 2>&1; then # if temp image exists
        docker rmi temp || { echo "ERROR: failed at $BASH_SOURCE:$LINENO" >&2; return 1; }
    fi
    return 0
}

function get_docker_hash_for_image {
    docker history $1 | head -n 2 | tail -n 1 | awk '{print $1}'
}

main "$@"
