name: 'Install vault and other utilities'
description: 'Installs vault, curl, unzip and jq to use in other workflows'
runs:
  using: 'composite'
  steps:
    - name: Install vault and utils
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get -y install curl unzip jq
        sudo curl -O https://releases.hashicorp.com/vault/1.9.0/vault_1.9.0_linux_amd64.zip
        sudo unzip vault_1.9.0_linux_amd64.zip
        sudo mv vault /usr/local/bin
