name: 'Authenticate into Dockerhub with stored credentials'
description: 'Pulls credentials from vault and runs docker login'
inputs:
  vault_addr:
    description: 'vault API endpoint'
    required: true
  vault_role_id:
    description: 'vault role for accessing secrets'
    required: true
  vault_secret_id:
    description: 'credential to authenticate into vault'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Extract main service account json
      uses: ./.github/actions/extract-vault-secret-to-file
      with:
        vault_secret_path: 'secret/kdux/scp/production/scp_dockerhub_credentials.json'
        vault_addr: ${{ inputs.VAULT_ADDR }}
        vault_role_id: ${{ inputs.VAULT_ROLE_ID }}
        vault_secret_id: ${{ inputs.VAULT_SECRET_ID }}
        output_filename: 'credentials.env'
        output_format: 'env'
    - name: Authenticate to dockerhub
      shell: bash
      run: |
        . ./credentials.env
        echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      
