name: Publish rails-baseimage Docker image
on:
  push:
    branches:
      - master
  workflow_dispatch:
env:
  VAULT_SECRET_PATH: 'secret/kdux/scp/staging/scp_service_account.json'
  IMAGE_NAME: 'gcloud-config'

jobs:
  Build-And-Publish-Docker-Image:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Configure gcloud container and activate service account
        uses: ./.github/actions/configure-gcloud-container
        with:
          vault_secret_path: ${{ env.VAULT_SECRET_PATH }}
          vault_addr: ${{ secrets.VAULT_ADDR }}
          vault_role_id: ${{ secrets.VAULT_ROLE_ID }}
          vault_secret_id: ${{ secrets.VAULT_SECRET_ID }}
      - name: Authenticate to docker
        shell: bash
        run: |
          # auth into GCR via Docker with token from service account
          AUTH_TOKEN=$(docker run --rm ${{ env.IMAGE_NAME }} gcloud auth print-access-token)
          # need separate logins for gcr.io & marketplace.gcr.io
          echo $AUTH_TOKEN | docker login -u oauth2accesstoken --password-stdin https://gcr.io
          echo $AUTH_TOKEN | docker login -u oauth2accesstoken --password-stdin https://marketplace.gcr.io
      - name: Build and publish base Docker image
        id: build-and-publish
        continue-on-error: true
        run: |
          ci/gha.publish-image.bash
          echo "exit-code=$?" >> $GITHUB_OUTPUT
      - name: Set exit code
        uses: ./.github/actions/set-exit-code
        with:
          exit-code: ${{ steps.build-and-publish.outputs.exit-code }}

