name: Publish rails-baseimage Docker image
on:
  push:
    branches:
      - master
  workflow_dispatch:
env:
  GOOGLE_PROJECT: 'broad-singlecellportal-staging'

jobs:
  Build-And-Publish-Docker-Image:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Configure gcloud
        uses: ./.github/actions/setup-gcloud
        with:
          service_account_email: '839419950053-compute@developer.gserviceaccount.com'
          google_cloud_project: 'broad-singlecellportal-staging'
      - name: Build and publish base Docker image
        id: build-and-publish
        run: |
          set +e # continue to allow capturing exit code
          ci/gha.publish-image.bash
          echo "exit-code=$?" >> $GITHUB_OUTPUT
      - name: Set exit code
        uses: ./.github/actions/set-exit-code
        with:
          exit-code: ${{ steps.build-and-publish.outputs.exit-code }}

