name: Test rails-baseimage Docker image
on:
  push:
    branches-ignore:
      - master
  workflow_dispatch:
  pull_request:
env:
  VAULT_SECRET_PATH: 'secret/kdux/scp/staging/scp_service_account.json'
  IMAGE_NAME: 'gcloud-config'

jobs:
  Build-And-Test-Docker-Image:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Configure gcloud container and activate service account
        uses: ./.github/actions/configure-gcloud-container
        with:
          vault_secret_path: ${{ env.VAULT_SECRET_PATH }}
          vault_addr: ${{ secrets.VAULT_ADDR }}
          vault_role_id: ${{ secrets.VAULT_ROLE_ID }}
          vault_secret_id: ${{ secrets.VAULT_SECRET_ID }}
      - name: Authenticate to GCR
        shell: bash
        run: |
          # auth into GCR via Docker with token from service account
          AUTH_TOKEN=$(docker run --rm ${{ env.IMAGE_NAME }} gcloud auth print-access-token)
          # need separate logins for gcr.io & marketplace.gcr.io
          echo $AUTH_TOKEN | docker login -u oauth2accesstoken --password-stdin https://gcr.io
          echo $AUTH_TOKEN | docker login -u oauth2accesstoken --password-stdin https://marketplace.gcr.io
      - name: Test candidate base Docker image
        id: build-and-test
        run: |
          set +e # continue on error to capture exit code
          ci/gha.build-and-test.bash
          exitcode="$?"
          echo "exitcode=$exitcode"
          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
      - name: Check for unstable build
        if: ${{ steps.build-and-test.exitcode == '99' }}
        run: |
          echo "### WARNING: THERE ARE UPDATED DEPENDENCIES, BUT THIS IMAGE WILL STILL FUNCTION ###"
          echo "### MARKING AS SUCCESSFUL ###"
          exit 0

