name: Test rails-baseimage Docker image
on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:
  pull_request:
env:
  GOOGLE_CLOUD_PROJECT: 'broad-singlecellportal-staging'

jobs:
  Build-And-Test-Docker-Image:
    runs-on: ubuntu-20.04
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Configure gcloud
        uses: ./.github/actions/setup-gcloud
        with:
          service_account_email: '839419950053-compute@developer.gserviceaccount.com'
          google_cloud_project: ${{ env.GOOGLE_CLOUD_PROJECT }}
      - name: Test candidate base Docker image
        id: build-and-test
        run: |
          set +e # continue to allow capturing exit code
          ci/gha.build-and-test.bash
          echo "exit-code=$?" >> $GITHUB_OUTPUT
      - name: Set exit code
        uses: ./.github/actions/set-exit-code
        with:
          exit-code: ${{ steps.build-and-test.outputs.exit-code }}
